spring.application.name=esports
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
server.port=8080
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=c:/Imagenes/
app.admin.username=admin
app.admin.password=admin1234

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/stadion?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:user_stadion}
spring.datasource.password=${DB_PASSWORD:user1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver